#include <memory>

#include "include/Lib1/Vigenere.h"

using std::make_unique;

/*
 * Test
 */
#include <string>
#include <map>
#include <vector>
#include <unordered_map>
#include <iostream>

using std::map;
using std::string;
using std::vector;
using std::unordered_map;
using std::cout;
using std::endl;


int main() {


    auto vig_entry = make_unique<Vigenere>();
    vig_entry->Start();

    /*
    string ciph = "NIGFMNGCGFBHISSMVWTLPFMJFUVSMSUSQFFUIFZWYSAQDJTWFVUVSWADHCSABBRFKJFSGGSQCOKVADUAPBOOVGCFPJESFHSUVSSAOUOMDFLONHMSGPXFOQIUMOGTAGWQBLJCBPXBTWFDECTLFPKZFVHSTPJSSGFSSQVBFETCSVJGDMSZKOTLISDVJQCGFSTOAFJJQOOUPZZFYFGUSWXWBUZFQSOLVFMUZFMRFNFZCQWEHVFASCKOFBHISSMVWTLPFMDGMZSDLJCBTXPFHIWVGSPXUVSJJTHIEWOHGCQUVSMSTHEVSSHSSGGHVFUFBHVJZHVFKDWSOLJTWDJFGSBJDVWOLISIOAWSFTAUWSTOBGGIAGHWOYUCKBJEPWPDPUWDSMFSTWBFQIGOOQFDMIZBJMSJFDBBRDMUHWOYFRUFJFGSBJDVAPNFRTSGNAITWVAGUGVBWWWSGWUQMOPPJBHCSAFGKIAMSABFZZOSYFAITWVAGTMDVOTLISGNAUVGPFJOBJFTHWUMUWCOSSSGUAMZFFKQSQUWEOGSWTSOSUIQSOLFFGSWTSOSUIWGOGMCBHWSOABAODISHPGSPXNCGUEVGSVETKVJDFHVFJFWGBFPBUPAOURFTBHSBTPIHUZFDISHPGSTGGWBUWSDFFLBHWPFPTONMTSINKDCZMWDHWPFUVSSWIOGCWFBODGOGWTLFBHNATGWPFUCDSGUSQUSORDSWTSFWWBFHJXBQHTXPFTVLVFSHWOSFBLJCBTEVQVDSSSSYHFFHJKFOBEWYDSOKFWGJFWSGUWEWBQJFGSSNBHWPFFTTPJUGHPJFHOSVESQPEQCGJLJCBJFBUWOYECQVEFBHTSSHWGSDHGBJUKCSCTOBETVWZEAOUGBDMAITWVAGEATDZBQPPXFUUGHISUOFFANDCSLBBHUGBQIMLVFSBKIWGUGSWOOKUSJFFDCBOOSWHFKUCGFWUVSUZJBUJLTSZGOJHVPFFGCXFFMSTSORWOSQIPMADDZBUFGISJPIBEWEPMPLISFQWPDZFZBJWOYTCAFNFFGJGOCTUZFGONWFLDFJJSBDWDOBCWFBQISOHWOY";
    */

    return 0;
}